# inherit_gem:
#   tt_ruby_style:
#     - default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'db/schema.rb'

# Eats a lot of the upper section space
Style/FrozenStringLiteralComment:
  Enabled: false

# Why not?
Style/LambdaCall:
  Enabled: false

# Sometimes can be useful to chain blocks
Style/MultilineBlockChain:
  Enabled: false

# Don't think we should document any files
Style/Documentation:
  Enabled: false

# Class::() {} - looks fine to me
Style/ColonMethodCall:
  Enabled: false

# Eats the indentation level
Style/ClassAndModuleChildren:
  Enabled: false

# Писать комменты на русском
Style/AsciiComments:
  Enabled: false

# SOAP involves camelcase methods like GetActionName
Naming/AccessorMethodName:
  Exclude:
    - app/soap/*.rb

Security/Eval:
  Enabled: false

# Specs size could be enormous
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ParameterLists:
  CountKeywordArgs: false


Style/IfUnlessModifier:
  Enabled: false

  