# Offense count: 26
Metrics/AbcSize:
  Max: 50

# Offense count: 85
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 203

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 120

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 7

# Offense count: 20
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 41

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 200

# Offense count: 2
Metrics/PerceivedComplexity:
  Max: 8

# Offense count: 708
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 149

# TODO: remove
Style/GlobalVars:
  Enabled: false
